services:
  - type: web
    name: frontend
    env: docker
    repo: https://github.com/RandomStudio/Chatbots-for-spatial-Director
    dockerfilePath: frontend/Dockerfile
    plan: free
    autoDeploy: true

  - type: web
    name: backend
    env: docker
    repo: https://github.com/RandomStudio/Chatbots-for-spatial-Director
    dockerfilePath: backend/Dockerfile
    plan: free
    autoDeploy: true
